language: node_js
sudo: false
node_js:
  - "0.12"
  - "4"
  - "node"
before_script:
  - npm install istanbul coveralls
script:
  - istanbul cover ./tests/index.js
after_success:
  - coveralls < coverage/lcov.info

